### ISSUE TITLE
Excluded Apps not working(vscode) & polluting the clipboard 

### ISSUE THREAD

**Issue by Alivers** [laike9m/Xylect#5] opened 2024-11-27 11:14 UTC
1. When I set vscode to the `excluded apps`, it still show the icon when I select texts.
2. Sometimes the selected contents were copied to my clipboard(I'm using Alfred).

**Comment by laike9m** [comment] 2024-11-27 14:22
Noted. I'll take a look. In the short-term, using keyboard shortcut mode
should help.

Aliver ***@***.***> 于 2024年11月27日周三 上午3:14写道：

**Comment by laike9m** [comment] 2024-11-28 05:01
@Alivers For 2, could you post a screenshot to help me understand the problem. I'm trying to understand in what app you made the selection (is it Alfred?)

**Comment by Alivers** [comment] 2024-11-28 05:36
@laike9m Sorry, I didn't describe it accurately. When I select some texts (which will be with a highlighted background) and then double-click or triple-click the text(sometime even no clicking), it gets copied to the clipboard. This happens in most apps (like Chrome, Telegram, email, etc.). I'm using Alfred to keep my clipboard history, so I noticed the clipboard has been polluted.

**Comment by laike9m** [comment] 2024-11-28 06:00
Got it, I can confirm this is a bug

**Comment by laike9m** [comment] 2024-11-28 07:44
Hi, 1.12.3 should have fixed problem 1, let me know if it works.

I still need some time to debug 2

**Comment by Alivers** [comment] 2024-11-28 07:49
Yeah, the apps excluded as expected. Thank you!

**Comment by laike9m** [comment] 2024-12-03 01:39
Hi @Alivers, for some reason I cannot reproduce the clipboard bug anymore.

Can you send me the log if the issue still happens?
https://github.com/laike9m/Xylect/issues/13

**Comment by laike9m** [comment] 2024-12-05 02:32
Closed as I can't reproduce. Feel free to reopen.

**Closed by laike9m** 2024-12-05 02:32 UTC
Labels: bug
